### ISSUE TITLE
Deprecated Properties used in flutter_admin_scaffold

### ISSUE THREAD

**Issue by devmarwat** [keyber-inc/flutter_admin_scaffold#14]
As the package is not been updated for a long time and with the new release of flutter, backwardsCompatibility, textTheme, and brightness properties are deprecated now. So, update the Packacage because new users testing your package face issues in which they don't understand how to use Flutter_admin_scaffold.

Following are the error during compilation
      brightness: appBar.brightness,
      ^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/material/app_bar.dart:177:3: Context: Found this candidate, but the arguments don't match.
  AppBar({
  ^^^^^^
/C:/Users/ONE/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_admin_scaffold-1.1.2/lib/admin_scaffold.dart:238:7: Error: No named parameter with the name 'textTheme'.
      textTheme: appBar.textTheme,
      ^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/material/app_bar.dart:177:3: Context: Found this candidate, but the arguments don't match.

  AppBar({
  ^^^^^^
/C:/Users/ONE/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_admin_scaffold-1.1.2/lib/admin_scaffold.dart:247:7: Error: No named parameter with the name 'backwardsCompatibility'.
      backwardsCompatibility: appBar.backwardsCompatibility,
      ^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/material/app_bar.dart:177:3: Context: Found this candidate, but the arguments don't match.
  AppBar({
  ^^^^^^

**Comment by devmarwat** [comment]
For now, until the issue is resolved, above mentioned errors can be solved just by following below steps
1> open file C:\Users\"PC User Name"\AppData\Local\Pub\Cache\hosted\pub.dev\flutter_admin_scaffold-1.1.2\lib
note: PC User Name" is the name of the Windows User, 
or Directly from your project click and open 'AdminScaffold' file 
2> go to line number 235, 238, and 247 and comment them, save the file and your project again.
The same steps should be repeated again after running flutter clean and flutter pub get

**Comment by susatthi** [comment]
Thank you for contacting us! v1.2.0 released 🎉

https://pub.dev/packages/flutter_admin_scaffold/changelog
