### ISSUE TITLE
Customizing the Color of the Drawer Button in the Top Left Corner

### ISSUE THREAD

**Issue by loye22** [keyber-inc/flutter_admin_scaffold#24]
Hey hope this msg find you well. 

Is there a way to customize the color of the drawer button in the top left corner?

![Screenshot from 2024-12-19 13-13-29](https://github.com/user-attachments/assets/ce7563a0-73e7-4ed0-bb31-2843d4d3f4b1)

**Comment by susatthi** [comment]
@loye22 

Added the leadingIcon parameter in version 1.4.0!

**Comment by loye22** [comment]
Thank you!!
