### ISSUE TITLE
menue item is not defined

### ISSUE THREAD

**Issue by shahid123-hue** [keyber-inc/flutter_admin_scaffold#6]
MenuItem' isn't a function. (Documentation)  Try correcting the name to match an existing function, or define a method or function named 'MenuItem'.
The name 'MenuItem' is defined in the libraries 'package:flutter/src/widgets/platform_menu_bar.dart' and 'package:flutter_admin_scaffold/src/menu_item.dart (via package:flutter_admin_scaffold/admin_scaffold.dart)'. (Documentation)  Try using 'as prefix' for one of the import directives, or hiding the name from all but one of the imports.

**Comment by shahid123-hue** [comment]
how to solve

**Comment by susatthi** [comment]
@shahid123-hue 

see: https://stackoverflow.com/questions/19723063/what-is-the-difference-between-show-and-as-in-an-import-statement

example:

```
import `package:flutter_admin_scaffold/admin_scaffold.dart` hide MenuItem;
```

or

```
import `package:flutter_admin_scaffold/admin_scaffold.dart` as admin_scaffold;
```

try it!
