### ISSUE TITLE
MenuItem with Flutter 3.0.0

### ISSUE THREAD

**Issue by IgorGZd** [keyber-inc/flutter_admin_scaffold#7]
With new Flutter 3.0.0 there is error on MenuItem class name. 
Need rename on import. Example: import 'menu_item.dart' as omi; and use as omi.MenuItem.

**Comment by susatthi** [comment]
@IgorGZd 

Thank you for teaching me! I Fixed the issue and updated v1.1.1 to pub.dev. Look carefully at the change log.

https://pub.dev/packages/flutter_admin_scaffold/changelog

This issue closes.

**Comment by IgorGZd** [comment]
Thanks for the very quick solution!
